#fourth_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  four_wheel_steering_controller:
    type        : "four_wheel_steering_controller/FourWheelSteeringController"
    front_wheel: ['joint31', 'joint41']
    rear_wheel: ['joint11', 'joint22']
    front_steering: ['joint3', 'joint4']
    rear_steering: ['joint1', 'joint2']
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    cmd_vel_timeout: 25.0 # not tested here

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.930
    wheel_radius : 0.046
    wheel_steering_y_offset : 0.03

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
    
    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : false
        # max_velocity           : 5  # m/s
        # min_velocity           : -5 # m/s
        has_acceleration_limits: false
        max_acceleration       : 5  # m/s^2
        min_acceleration       : -5 # m/s^2
    angular:
      z:
        has_velocity_limits    : false
        # max_velocity           : 3.14  # rad/s
        # min_velocity           : -3.14
        has_acceleration_limits: false
        # max_acceleration       : 1.0  # rad/s^2
        # min_acceleration       : -1.0

    /gazebo_ros_control:
      pid_gains:
        joint1:
          p: 200
          i: 1
          d: 0.01
        joint2:
          p: 200
          i: 1
          d: 0.01
        joint3:
          p: 200
          i: 1
          d: 0.01
        joint4:
          p: 200
          i: 1
          d: 0.01
        joint11: #front_left_wheel
          p: 10
          i: 1
          d: 0.0
        joint22: #front_right_wheel
          p: 10
          i: 1
          d: 0.0
        joint31: #rear_left_wheel
          p: 10
          i: 1
          d: 0.0
        joint41: #rear_right_wheel
          p: 10
          i: 1
          d: 0.0
